/*global systemDictionary:true */
'use strict';

systemDictionary = {
	'swissglider1adapter adapter settings': {
		en: 'Adapter settings for swissglider1adapter',
		de: 'Adaptereinstellungen für swissglider1adapter',
		ru: 'Настройки адаптера для swissglider1adapter',
		pt: 'Configurações do adaptador para swissglider1adapter',
		nl: 'Adapterinstellingen voor swissglider1adapter',
		fr: "Paramètres d'adaptateur pour swissglider1adapter",
		it: "Impostazioni dell'adattatore per swissglider1adapter",
		es: 'Ajustes del adaptador para swissglider1adapter',
		pl: 'Ustawienia adaptera dla swissglider1adapter',
		'zh-cn': 'swissglider1adapter的适配器设置',
	},
	'loading...': {
		en: 'loading...',
		de: 'Wird geladen...',
		ru: 'загрузка ...',
		pt: 'Carregando...',
		nl: 'bezig met laden...',
		fr: 'chargement...',
		it: 'Caricamento in corso...',
		es: 'cargando...',
		pl: 'Ładuję...',
		'zh-cn': '载入中...',
	},
	state1ToShow: {
		en: 'First Test State to show EN',
		de: 'Erster Status welcher gezeigt wird !',
		ru: 'First Test State to show RU',
		pt: 'First Test State to show PT',
		nl: 'First Test State to show NL',
		fr: 'First Test State to show FR',
		it: 'First Test State to show IT',
		es: 'First Test State to show ES',
		pl: 'First Test State to show PL',
		'zh-cn': 'First Test State to show ZH-CN',
	},
	state2ToShow: {
		en: 'Second Test State to show EN',
		de: 'Zweiter Status welcher gezeigt wird !',
		ru: 'Second Test State to show RU',
		pt: 'Second Test State to show PT',
		nl: 'Second Test State to show NL',
		fr: 'Second Test State to show FR',
		it: 'Second Test State to show IT',
		es: 'Second Test State to show ES',
		pl: 'Second Test State to show PL',
		'zh-cn': 'Second Test State to show ZH-CN',
	},
	objectToShow: {
		en: 'First Test Object to show EN',
		de: 'Erstes Object welcher gezeigt wird !',
		ru: 'First Test Object to show RU',
		pt: 'First Test Object to show PT',
		nl: 'First Test Object to show NL',
		fr: 'First Test Object to show FR',
		it: 'First Test Object to show IT',
		es: 'First Test Object to show ES',
		pl: 'First Test Object to show PL',
		'zh-cn': 'First Test Object to show ZH-CN',
	},
	send_new_Message: {
		en: 'Send a Hello to the adapter EN',
		de: 'Sende ein Hallo an den Adapter !',
		ru: 'Send a Hello to the adapter RU',
		pt: 'Send a Hello to the adapter PT',
		nl: 'Send a Hello to the adapter NL',
		fr: 'Send a Hello to the adapter FR',
		it: 'Send a Hello to the adapter IT',
		es: 'Send a Hello to the adapter ES',
		pl: 'Send a Hello to the adapter PL',
		'zh-cn': 'Send a Hello to the adapter ZH-CN',
	},
};
